### ISSUE TITLE
Running `cargo test` fails to No such file or directory (os error 2)', src/filter.rs:143:14

### ISSUE THREAD

**Issue by juippis** [InputUsername/rescrobbled#109]
```
running 6 tests
test config::tests::test_normalize_empty_config ... ok
test config::tests::test_normalize_listenbrainz_double ... ok
test config::tests::test_normalize_listenbrainz_token ... ok
test track::tests::test_new ... ok
test track::tests::test_from_metadata ... ok
test filter::tests::test_filter_script ... FAILED

failures:

---- filter::tests::test_filter_script stdout ----
thread 'filter::tests::test_filter_script' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to run filter script at /tmp/.tmp2GyI94/filter.sh

Caused by:
    No such file or directory (os error 2)', src/filter.rs:143:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    filter::tests::test_filter_script

test result: FAILED. 5 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

```

Indeed the file or the directory under */tmp* doesn't exist.

**Comment by InputUsername** [comment]
Thanks for reporting. The test creates executable `.sh` files in a temp directory under `/tmp`, the error suggests those scripts aren't there when the test tries to run them. Is your OS doing something funky with `/tmp`?

**Comment by juippis** [comment]
Not to my knowledge :) it's not even a *tmpfs* partition in this case. And shouldn't be permission related problem as I was running the **cargo test** command as root.

**Comment by InputUsername** [comment]
@juippis Honestly a bit stumped by this haha :sweat_smile: The test runs fine on my machines (Fedora 38) and GitHub's CI runners (Ubuntu 22.X iirc).

As a shot in the dark, could you try running the test with the following changes?
```diff
diff --git a/src/filter.rs b/src/filter.rs
index 0e67eeb..cdbf129 100644
--- a/src/filter.rs
+++ b/src/filter.rs
@@ -118,9 +118,8 @@ mod tests {
     #[test]
     fn test_filter_script() {
         let mut config = Config::default();
-        let temp_dir = tempfile::tempdir().unwrap();
 
-        let path = temp_dir.path().join("filter.sh");
+        let path = std::env::temp_dir().join("filter.sh");
         const FILTER_SCRIPT: &str = "#!/usr/bin/bash
 read artist
 read title
@@ -150,7 +149,7 @@ echo \"Album=$album\"
 
         // Script that produces no output should result in `FilterResult::Ignored`
 
-        let path_ignore = temp_dir.path().join("filter_ignore.sh");
+        let path_ignore = std::env::temp_dir().join("filter_ignore.sh");
         const FILTER_SCRIPT_IGNORE: &str = "#!/usr/bin/bash
 true
 ";
@@ -185,7 +184,7 @@ true
 
         // Album should be optional, empty album should still result in `FilterResult::Filtered`
 
-        let path_no_album = temp_dir.path().join("filter_no_album.sh");
+        let path_no_album = std::env::temp_dir().join("filter_no_album.sh");
         const FILTER_SCRIPT_NO_ALBUM: &str = "#!/usr/bin/bash
 read artist
 read title
```

**Comment by juippis** [comment]
Unfortunately it doesn't work :(

```
running 6 tests
test config::tests::test_normalize_empty_config ... ok
test config::tests::test_normalize_listenbrainz_double ... ok
test config::tests::test_normalize_listenbrainz_token ... ok
test track::tests::test_new ... ok
test track::tests::test_from_metadata ... ok
test filter::tests::test_filter_script ... FAILED

failures:

---- filter::tests::test_filter_script stdout ----
thread 'filter::tests::test_filter_script' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to run filter script at /tmp/filter.sh

Caused by:
    No such file or directory (os error 2)', src/filter.rs:142:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    filter::tests::test_filter_script

test result: FAILED. 5 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```
What's weird that the file does exist now:
`/tmp/filter.sh: Bourne-Again shell script, ASCII text executable`

```
# RUST_BACKTRACE=full cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.02s
warning: the following packages contain code that will be rejected by a future version of Rust: wrapped-vec v0.3.0
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 2`
     Running unittests src/main.rs (target/debug/deps/rescrobbled-fde04184bacbbff5)

running 6 tests
test config::tests::test_normalize_empty_config ... ok
test config::tests::test_normalize_listenbrainz_double ... ok
test config::tests::test_normalize_listenbrainz_token ... ok
test track::tests::test_new ... ok
test track::tests::test_from_metadata ... ok
test filter::tests::test_filter_script ... FAILED

failures:

---- filter::tests::test_filter_script stdout ----
thread 'filter::tests::test_filter_script' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to run filter script at /tmp/filter.sh

Caused by:
    No such file or directory (os error 2)', src/filter.rs:142:14
stack backtrace:
   0:     0x5649d2a0391a - std::backtrace_rs::backtrace::libunwind::trace::h9a6b80bbf328ba5d
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5649d2a0391a - std::backtrace_rs::backtrace::trace_unsynchronized::hd162ec543a11886b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5649d2a0391a - std::sys_common::backtrace::_print_fmt::h78a5099be12f51a6
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x5649d2a0391a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha1c5390454d74f71
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5649d2a277af - core::fmt::write::h9ffde816c577717b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/fmt/mod.rs:1254:17
   5:     0x5649d2a003d5 - std::io::Write::write_fmt::he46c30c8efa4339b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/io/mod.rs:1698:15
   6:     0x5649d2a036e5 - std::sys_common::backtrace::_print::h184198273ed08d59
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x5649d2a036e5 - std::sys_common::backtrace::print::h1b4d8e7add699453
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x5649d2a0539e - std::panicking::default_hook::{{closure}}::h393bcea75423915a
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:269:22
   9:     0x5649d2a050d1 - std::panicking::default_hook::h48c64f31d8b3fd03
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:285:9
  10:     0x5649d29bc29b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h04e5a570f98d94a5
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1987:9
  11:     0x5649d29bc29b - test::test_main::{{closure}}::h35282677eae04491
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/test/src/lib.rs:134:21
  12:     0x5649d2a05a84 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hb9b860f5a1175bda
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1987:9
  13:     0x5649d2a05a84 - std::panicking::rust_panic_with_hook::hafdc493a79370062
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:695:13
  14:     0x5649d2a057f9 - std::panicking::begin_panic_handler::{{closure}}::h0a64bc82e36bedc7
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
  15:     0x5649d2a03d86 - std::sys_common::backtrace::__rust_end_short_backtrace::hc203444fb7416a16
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
  16:     0x5649d2a05552 - rust_begin_unwind
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
  17:     0x5649d296fc93 - core::panicking::panic_fmt::h0f6ef0178afce4f2
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
  18:     0x5649d29701d3 - core::result::unwrap_failed::h8090202169109f9c
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1687:5
  19:     0x5649d297e68d - core::result::Result<T,E>::unwrap::h26cbbea8e958d916
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1089:23
  20:     0x5649d297674f - rescrobbled::filter::tests::test_filter_script::h47d98ea5f548bf48
                               at /var/tmp/portage/media-sound/rescrobbled-0.7.1/work/rescrobbled-0.7.1/src/filter.rs:137:13
  21:     0x5649d2975587 - rescrobbled::filter::tests::test_filter_script::{{closure}}::hc7946b7cf054723b
                               at /var/tmp/portage/media-sound/rescrobbled-0.7.1/work/rescrobbled-0.7.1/src/filter.rs:119:29
  22:     0x5649d297aca5 - core::ops::function::FnOnce::call_once::h8b860b8462420f0f
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
  23:     0x5649d29c110f - core::ops::function::FnOnce::call_once::hafae920b9cfffa5c
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
  24:     0x5649d29c110f - test::__rust_begin_short_backtrace::h4dab7d6a08f0d362
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/test/src/lib.rs:655:18
  25:     0x5649d298e7bc - test::run_test::{{closure}}::h5777daa7f3526fb4
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/test/src/lib.rs:646:30
  26:     0x5649d298e7bc - core::ops::function::FnOnce::call_once{{vtable.shim}}::hd95ab3f789a2e622
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
  27:     0x5649d29c0246 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9b5ece2761ae65f4
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
  28:     0x5649d29c0246 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h548d7ffd73c811c0
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panic/unwind_safe.rs:271:9
  29:     0x5649d29c0246 - std::panicking::try::do_call::h854a5228fe1e95dc
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  30:     0x5649d29c0246 - std::panicking::try::hb9b581309100ec61
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  31:     0x5649d29c0246 - std::panic::catch_unwind::hfa310295f4e4548a
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  32:     0x5649d29c0246 - test::run_test_in_process::h611ba57bef59388b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/test/src/lib.rs:678:27
  33:     0x5649d29c0246 - test::run_test::run_test_inner::{{closure}}::h02b437db2c35fa59
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/test/src/lib.rs:572:39
  34:     0x5649d2989165 - test::run_test::run_test_inner::{{closure}}::hac022141ed6ee1cc
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/test/src/lib.rs:599:37
  35:     0x5649d2989165 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc0afb33717ef09ec
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:134:18
  36:     0x5649d298e841 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h59a380c33e5b9be7
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/mod.rs:526:17
  37:     0x5649d298e841 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h282a80e3214c5689
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panic/unwind_safe.rs:271:9
  38:     0x5649d298e841 - std::panicking::try::do_call::hb39b3e6aa0172571
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  39:     0x5649d298e841 - std::panicking::try::h8b8c5d101d34c1ef
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  40:     0x5649d298e841 - std::panic::catch_unwind::hf0a845ca5c4da7bb
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  41:     0x5649d298e841 - std::thread::Builder::spawn_unchecked_::{{closure}}::hfae47c41df4c0a9d
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/mod.rs:525:30
  42:     0x5649d298e841 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hfd3e682bad8fc5a8
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
  43:     0x5649d2a0a085 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha1f2224656a778fb
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
  44:     0x5649d2a0a085 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::haa29ed9703f354b7
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
  45:     0x5649d2a0a085 - std::sys::unix::thread::Thread::new::thread_start::h33b6dae3e3692197
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys/unix/thread.rs:108:17
  46:     0x7f8dd63d0279 - <unknown>
  47:     0x7f8dd645331c - <unknown>
  48:                0x0 - <unknown>


failures:
    filter::tests::test_filter_script

test result: FAILED. 5 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

error: test failed, to rerun pass `--bin rescrobbled`
```

**Comment by InputUsername** [comment]
@juippis Is there a reason you're running tests as root? Does it work if you run without elevated permissions?

Also, what OS are you using? Does your OS treat subprocesses of programs that are run as root differently (i.e. child processes don't have root access)? Maybe that could explain why the child cannot access the file created by the parent process.

Very confusing issue

**Comment by juippis** [comment]
Hmm you might be on to something. I've been running these tests in an unprivileged container (hence the root user, root in container is uidmapped to my normal user in host). Now I tried with a normal user in the host system and it works. I don't understand why though, the container shouldn't have any such quirks and other rust programs that I've tested have worked fine :\

**Comment by juippis** [comment]
Unfortunately not, I updated *src/filter.rs* with 
```diff
-fs::set_permissions(path, fs::Permissions::from_mode(0o755)).unwrap();
+fs::set_permissions(path, fs::Permissions::from_mode(0o777)).unwrap();
```
but it didn't help :( with your changes from above the file gets created in */tmp* and now with permissions `-rwxrwxrwx`

**Comment by InputUsername** [comment]
I realize I never got back to this, sorry. Very weird issue. Is there any specific reason you're trying to run the tests from inside a container?

**Comment by juippis** [comment]
Hey, 

I'm sorry too. I've been meaning to dig into this, but frankly I forgot. To answer your question: I package different software and test that they build on "isolated" systems to try and cover as many use cases as possible. I find containers (lxd, incus) to be best for this, as it doesn't interfere with my main OS. This is probably a "me" issue so I'm fine closing this, but I'll try to figure more out hopefully next week.

**Comment by InputUsername** [comment]
@juippis I received a patch that should fix the issue! Apparently the error is caused by the fact that the filter scripts use Bash which may not be installed on all systems.

Could you try the latest commit on the development branch to see if it works?

**Comment by juippis** [comment]
Wow, indeed it did pass!
```
running 6 tests
test config::tests::test_normalize_empty_config ... ok
test config::tests::test_normalize_listenbrainz_double ... ok
test config::tests::test_normalize_listenbrainz_token ... ok
test track::tests::test_from_metadata ... ok
test track::tests::test_new ... ok
test filter::tests::test_filter_script ... ok

test result: ok. 6 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s
```

To me it sounds a bit weird since I've always used bash, but hey whatever.

I was chasing a totally different edge, "cargo tmpdir noexec" even though I didn't have tmpfs but search results seemed to match there best. 

Glad to see it works :) thanks!
